### ISSUE TITLE
Typo -- "blocl" should be "block"

### ISSUE THREAD

**Issue by alichtman** [dotfm/ONE-Tough-Cookie#1]
https://github.com/dotfm/ONE-Tough-Cookie/blob/c38a14a32cd891273e0cd141650707119fca7d1a/ubo#L37

--

I like seeing people riff off my work - glad to have inspired you!

**Comment by dotfm** [comment]
thx bro :) 👍 
btw, stronghold's is the shiznit ! (nice work!)
though, if i may...i'm completely down with chmod'ng the metadata folder w/in ~/Lib; but what if we'd switch it out with some sort of 'cron-like' script(running on the hour, or at each logout; i dunno[this literally just came to me]...); where instead of chmod000/uchflags; we'd run xattr striping all kMD::Metadata. (Or maybe have it overwrite the original hexs with plain 00s)

**Comment by alichtman** [comment]
> btw, stronghold's is the shiznit ! (nice work!)

Thanks dude!

> though, if i may...i'm completely down with chmod'ng the metadata folder w/in ~/Lib; but what if we'd switch it out with some sort of 'cron-like' script(running on the hour, or at each logout; i dunno[this literally just came to me]...); where instead of chmod000/uchflags; we'd run xattr striping all kMD::Metadata. (Or maybe have it overwrite the original hexs with plain 00s)

Drop this idea in an issue on stronghold. I want to think about this further...
